name: Store readme in Drive
on:
  push: { branches: [challenge] }
jobs:
  buildAndTestForSomePlatforms:
    name: Upload readme to drive
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      # Upload to Drive
      - name: Upload public folder to Google Drive
        uses: Jodebu/upload-to-drive@master
        id: driveUpload
        with:
          target: README.md
          credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          folder: ${{ secrets.GOOGLE_DRIVE_FOLDER }}
