name: Store readme in Drive
on:
  push: { branches: [challenge] }
jobs:
  buildAndTestForSomePlatforms:
    name: Upload readme to drive
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: .github/workflows/
          recursive: true
          dest: builds.zip
      # Upload to Drive
      - name: Upload public folder to Google Drive
        # uses: Jodebu/upload-to-drive@master
        # id: driveUpload
        # with:
        #   target: README.md
        #   credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        #   folder: 1nuEl638ycrSlfm6uBSez6IWoCH5aGZF1
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          filename: builds.zip
          folderId: 1nuEl638ycrSlfm6uBSez6IWoCH5aGZF1
