name: Store readme in Drive
on:
  push: { branches: [challenge] }
jobs:
  buildAndTestForSomePlatforms:
    name: Upload readme to drive
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+05:45"
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: .github/workflows/
          recursive: true
          dest: builds-${{ steps.date.outputs.date }}.zip
      # Upload to Drive
      - name: Upload public folder to Google Drive
        # uses: Jodebu/upload-to-drive@master
        # id: driveUpload
        # with:
        #   target: README.md
        #   credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        #   folder: 1nuEl638ycrSlfm6uBSez6IWoCH5aGZF1
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          filename: builds-${{ steps.date.outputs.date }}.zip
          overwrite: true
          folderId: 1nuEl638ycrSlfm6uBSez6IWoCH5aGZF1
